### ISSUE TITLE
No vmlinuz found with gentoo-kernel-bin-6.9.3 (arm64): "not recognized as any special format and unable to find version string in it"

### ISSUE THREAD

**Issue by sbraz** [projg2/eclean-kernel#52]
Hi, can you help me understand what's going on here please?
```
# eclean-kernel -D
DEBUG:root:Sorter: <ecleankernel.sort.VersionSort object at 0xffffaa68bf10>
DEBUG:root:Layout: <ecleankernel.layout.blspec.BlSpecLayout object at 0xffffaa66b550>
DEBUG:root:Bootloader failed: <class 'ecleankernel.bootloader.lilo.LILO'>
DEBUG:root:Bootloader failed: <class 'ecleankernel.bootloader.grub2.GRUB2'>
DEBUG:root:Bootloader failed: <class 'ecleankernel.bootloader.grub.GRUB'>
DEBUG:root:Bootloader failed: <class 'ecleankernel.bootloader.yaboot.Yaboot'>
DEBUG:root:Bootloader: <ecleankernel.bootloader.symlinks.Symlinks object at 0xffffaafe8350>
DEBUG:root:Unrecognized potential kernel image: Kernel file /efi/096c976bec474096a295d1e643e5291d/6.9.3-gentoo-dist/linux not recognized as any special format and unable to find version string in it
DEBUG:root:in get_removal_list()
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/eclean-kernel", line 8, in <module>
    sys.exit(setuptools_main())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ecleankernel/__main__.py", line 391, in setuptools_main
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ecleankernel/__main__.py", line 251, in main
    removals = get_removal_list(
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ecleankernel/process.py", line 81, in get_removal_list
    raise SystemError(
SystemError: No vmlinuz found. This seems ridiculous, aborting.
```

```
# file /efi/096c976bec474096a295d1e643e5291d/6.9.3-gentoo-dist/linux
/efi/096c976bec474096a295d1e643e5291d/6.9.3-gentoo-dist/linux: PE32+ executable (EFI application) Aarch64 (stripped to external PDB), for MS Windows, 2 sections
```

**Comment by leonik375** [comment]
I think new default gentoo kernel install procedure with Debian's 'installkernel' broke some things, installed kernels named "kernel-<version>-gentoo" by default now

**Comment by Nowa-Ammerlaan** [comment]
I'm pretty sure this is caused by `CONFIG_EFI_ZBOOT`. It makes the kernel an EFI application.

By the way, this kernel is installed in the layout for systemd-boot, but your second comment seems to suggest that this is not the bootloader you are using. Is this correct?

**Comment by Nowa-Ammerlaan** [comment]
Maybe you can give this patch a try and let us know if it helps: https://github.com/projg2/eclean-kernel/pull/53

**Comment by sbraz** [comment]
Thanks, it does work: https://github.com/projg2/eclean-kernel/pull/53#issuecomment-2439776144
